ALTER TABLE venta
  ADD COLUMN iva_base0      NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN iva_base5      NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN iva_valor5     NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN iva_base19     NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN iva_valor19    NUMERIC(18,2) NOT NULL DEFAULT 0;

ALTER TABLE factura
  ADD COLUMN iva_base0      NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN iva_base5      NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN iva_valor5     NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN iva_base19     NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN iva_valor19    NUMERIC(18,2) NOT NULL DEFAULT 0;
